create or replace PACKAGE BODY  PK_AMANDASOFT_PLUGINS AS


	--========================================================= FUNCIONES =============================================================================
	FUNCTION FC_LOAD_DATASOURCES(L_DATA_SOURCES IN VARCHAR2, L_TEMPLATE_URL IN VARCHAR2)
	RETURN VARCHAR2 IS

		L_CURSOR 										SYS_REFCURSOR;
		L_SQL_QUERY 								VARCHAR2(4000) 	:= '';
		L_ITEM_IN_LIST							VARCHAR2(4000) 	:= '';
		L_JSON_OBJECT 							VARCHAR2(4000);
		L_COUNTER										NUMBER := 1;
		L_QUERY_CURSOR							VARCHAR2(4000);

		CURSOR DATASOURCES IS
			SELECT REGEXP_SUBSTR(L_DATA_SOURCES,'[^,]+', 1, LEVEL) AS STR FROM DUAL
			CONNECT BY REGEXP_SUBSTR(L_DATA_SOURCES, '[^,]+', 1, LEVEL) IS NOT NULL;

	BEGIN

		FOR C IN DATASOURCES LOOP

			L_ITEM_IN_LIST := APEX_PLUGIN_UTIL.REPLACE_SUBSTITUTIONS('&'||C.STR||'.', FALSE) ;
			L_SQL_QUERY := APEX_PLUGIN_UTIL.REPLACE_SUBSTITUTIONS(L_ITEM_IN_LIST, FALSE) ;
			L_QUERY_CURSOR := L_QUERY_CURSOR||L_SQL_QUERY||'~';

		END LOOP;

		RETURN L_QUERY_CURSOR;

	END FC_LOAD_DATASOURCES;



	FUNCTION FC_RENDER_DOCXPRINTER
	(
		P_DYNAMIC_ACTION IN APEX_PLUGIN.T_DYNAMIC_ACTION,
		P_PLUGIN         IN APEX_PLUGIN.T_PLUGIN
	)
    RETURN APEX_PLUGIN.T_DYNAMIC_ACTION_RENDER_RESULT IS


		L_RESULT      								APEX_PLUGIN.T_DYNAMIC_ACTION_RENDER_RESULT;
		L_TEMPLATE_URL	 							VARCHAR2(4000) 	:= P_DYNAMIC_ACTION.ATTRIBUTE_01;
		L_PROCESS											VARCHAR2(4000) 	:= P_DYNAMIC_ACTION.ATTRIBUTE_02;
		L_DOCXOUT_NAME	 							VARCHAR2(4000) 	:= P_DYNAMIC_ACTION.ATTRIBUTE_03;
		L_DATA_SOURCES	 							VARCHAR2(4000) 	:= P_DYNAMIC_ACTION.ATTRIBUTE_04;
		L_TEMPLATE_VAL_RES						VARCHAR2(4000) 	:= P_DYNAMIC_ACTION.ATTRIBUTE_05;
		L_DATASOURCE_VAL_RES					VARCHAR2(4000) 	:= P_DYNAMIC_ACTION.ATTRIBUTE_06;
		L_DATASOURCE_VAL_ITM					VARCHAR2(4000) 	:= P_DYNAMIC_ACTION.ATTRIBUTE_07;
		L_JSON_OBJECT									CLOB;



	BEGIN

		APEX_PLUGIN_UTIL.DEBUG_DYNAMIC_ACTION
		(
			P_PLUGIN         => P_PLUGIN,
			P_DYNAMIC_ACTION => P_DYNAMIC_ACTION
		);

		APEX_JAVASCRIPT.ADD_LIBRARY
		(
			P_NAME                  => 'docxtemplater',
			P_DIRECTORY             => P_PLUGIN.FILE_PREFIX,
			P_CHECK_TO_ADD_MINIFIED => FALSE
		);

		APEX_JAVASCRIPT.ADD_LIBRARY
		(
			P_NAME                  => 'FileSaver',
			P_DIRECTORY             => P_PLUGIN.FILE_PREFIX,
			P_CHECK_TO_ADD_MINIFIED => FALSE
		);

		APEX_JAVASCRIPT.ADD_LIBRARY
		(
			P_NAME                  => 'jszip-utils',
			P_DIRECTORY             => P_PLUGIN.FILE_PREFIX,
			P_CHECK_TO_ADD_MINIFIED => FALSE
		);

		APEX_JAVASCRIPT.ADD_LIBRARY
		(
			P_NAME                  => 'jszip',
			P_DIRECTORY             => P_PLUGIN.FILE_PREFIX,
			P_CHECK_TO_ADD_MINIFIED => FALSE
		);

		APEX_JAVASCRIPT.ADD_LIBRARY
		(
			P_NAME                  => 'AmandaDocxPrinter',
			P_DIRECTORY             => P_PLUGIN.FILE_PREFIX,
			P_CHECK_TO_ADD_MINIFIED => FALSE
		);


		L_JSON_OBJECT := FC_LOAD_DATASOURCES(L_DATA_SOURCES, L_TEMPLATE_URL);

		L_RESULT.JAVASCRIPT_FUNCTION := 'amanda_docx_printer.init';
		L_RESULT.ATTRIBUTE_01 := V('APP_IMAGES')||L_TEMPLATE_URL;
		L_RESULT.ATTRIBUTE_02 := L_PROCESS;
		L_RESULT.ATTRIBUTE_03 := L_DOCXOUT_NAME;
		L_RESULT.ATTRIBUTE_04 := L_JSON_OBJECT;
		L_RESULT.ATTRIBUTE_05 := L_TEMPLATE_VAL_RES;
		L_RESULT.ATTRIBUTE_06 := L_DATASOURCE_VAL_RES;
		L_RESULT.ATTRIBUTE_07 := L_DATASOURCE_VAL_ITM;

		RETURN L_RESULT;


	END FC_RENDER_DOCXPRINTER;
	--=================================================================================================================================================

END PK_AMANDASOFT_PLUGINS;
