create or replace PACKAGE PK_AMANDASOFT_PLUGINS AS



	FUNCTION FC_RENDER_DOCXPRINTER
	(
		P_DYNAMIC_ACTION IN APEX_PLUGIN.T_DYNAMIC_ACTION,
		P_PLUGIN         IN APEX_PLUGIN.T_PLUGIN
	)
    RETURN APEX_PLUGIN.T_DYNAMIC_ACTION_RENDER_RESULT;





END PK_AMANDASOFT_PLUGINS;
